name: CytoCommunity
channels:
  - pyg
  - pytorch
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2

dependencies:
  - _r-mutex=1.0.0=anacondar_1
  - blas=2.116=mkl
  - blas-devel=3.9.0=16_win64_mkl
  - brotli=1.0.9=h8ffe710_7
  - brotli-bin=1.0.9=h8ffe710_7
  - brotlipy=0.7.0=py310he2412df_1004
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2022.07.19=haa95532_0
  - certifi=2022.9.24=py310haa95532_0
  - cffi=1.15.1=py310hcbf9ad4_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - colorama=0.4.5=pyhd8ed1ab_0
  - contourpy=1.0.5=py310h232114e_0
  - cpuonly=2.0=0
  - cryptography=37.0.1=py310h21b164f_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - fonttools=4.37.4=py310h8d17308_0
  - freetype=2.12.1=h546665d_0
  - gettext=0.19.8.1=h5728263_1009
  - glib=2.74.0=h12be248_0
  - glib-tools=2.74.0=h12be248_0
  - gst-plugins-base=1.20.3=h001b923_2
  - gstreamer=1.20.3=h6b5321d_2
  - icu=70.1=h0e60522_0
  - idna=3.4=pyhd8ed1ab_0
  - intel-openmp=2022.1.0=h57928b3_3787
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=h8ffe710_2
  - kiwisolver=1.4.4=py310h476a331_0
  - krb5=1.19.3=h1176d77_0
  - lcms2=2.12=h2a16943_0
  - lerc=4.0.0=h63175ca_0
  - libblas=3.9.0=16_win64_mkl
  - libbrotlicommon=1.0.9=h8ffe710_7
  - libbrotlidec=1.0.9=h8ffe710_7
  - libbrotlienc=1.0.9=h8ffe710_7
  - libcblas=3.9.0=16_win64_mkl
  - libclang=14.0.6=default_hf4acfee_0
  - libclang13=14.0.6=default_h8992b79_0
  - libdeflate=1.14=hcfcfb64_0
  - libffi=3.4.2=h8ffe710_5
  - libglib=2.74.0=h79619a9_0
  - libiconv=1.17=h8ffe710_0
  - liblapack=3.9.0=16_win64_mkl
  - liblapacke=3.9.0=16_win64_mkl
  - libogg=1.3.4=h8ffe710_1
  - libpng=1.6.38=h19919ed_0
  - libsqlite=3.39.4=hcfcfb64_0
  - libtiff=4.4.0=h8e97e67_4
  - libuv=1.44.2=h8ffe710_0
  - libvorbis=1.3.7=h0e60522_0
  - libwebp-base=1.2.4=h8ffe710_0
  - libxcb=1.13=hcd874cb_1004
  - libzlib=1.2.12=hcfcfb64_4
  - m2w64-bwidget=1.9.10=2
  - m2w64-bzip2=1.0.6=6
  - m2w64-expat=2.1.1=2
  - m2w64-fftw=3.3.4=6
  - m2w64-flac=1.3.1=3
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gettext=0.19.7=2
  - m2w64-gmp=6.1.0=2
  - m2w64-gsl=2.1=2
  - m2w64-libiconv=1.14=6
  - m2w64-libjpeg-turbo=1.4.2=3
  - m2w64-libogg=1.3.2=3
  - m2w64-libpng=1.6.21=2
  - m2w64-libsndfile=1.0.26=2
  - m2w64-libtiff=4.0.6=2
  - m2w64-libvorbis=1.3.5=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - m2w64-libxml2=2.9.3=4
  - m2w64-mpfr=3.1.4=4
  - m2w64-pcre2=10.34=0
  - m2w64-speex=1.2rc2=3
  - m2w64-speexdsp=1.2rc3=3
  - m2w64-tcl=8.6.5=3
  - m2w64-tk=8.6.5=3
  - m2w64-tktable=2.10=5
  - m2w64-wineditline=2.101=5
  - m2w64-xz=5.2.2=2
  - m2w64-zlib=1.2.8=10
  - markupsafe=2.1.1=py310he2412df_1
  - matplotlib=3.6.0=py310h5588dad_0
  - matplotlib-base=3.6.0=py310h51140c5_0
  - mkl=2022.1.0=h6a75c08_874
  - mkl-devel=2022.1.0=h57928b3_875
  - mkl-include=2022.1.0=h6a75c08_874
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyh9f0ad1d_0
  - networkx=2.8.7=pyhd8ed1ab_0
  - numpy=1.23.3=py310h4a8f9c9_0
  - openjpeg=2.5.0=hc9384bd_1
  - openssl=1.1.1q=h2bbff1b_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.5.0=py310h1c4a608_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pcre2=10.37=hdfff0fc_1
  - pillow=9.2.0=py310h52929f7_2
  - pip=22.2.2=pyhd8ed1ab_0
  - ply=3.11=py_1
  - pthread-stubs=0.4=hcd874cb_1001
  - pycparser=2.21=pyhd8ed1ab_0
  - pyg=2.0.4=py310_torch_1.11.0_cpu
  - pyopenssl=22.0.0=pyhd8ed1ab_1
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.7=py310hbabf5d4_0
  - pyqt5-sip=12.11.0=py310h8a704f9_0
  - pysocks=1.7.1=pyh0701188_6
  - python=3.10.6=h9a09f29_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-louvain=0.15=pyhd8ed1ab_1
  - python_abi=3.10=2_cp310
  - pytorch=1.11.0=py3.10_cpu_0
  - pytorch-cluster=1.6.0=py310_torch_1.11.0_cpu
  - pytorch-mutex=1.0=cpu
  - pytorch-scatter=2.0.9=py310_torch_1.11.0_cpu
  - pytorch-sparse=0.6.15=py310_torch_1.11.0_cpu
  - pytorch-spline-conv=1.2.1=py310_torch_1.11.0_cpu
  - pytz=2022.4=pyhd8ed1ab_0
  - pyyaml=6.0=py310he2412df_4
  - qt-main=5.15.6=hf0cf448_0
  - r-base=4.1.3=hddad469_1
  - requests=2.28.1=pyhd8ed1ab_1
  - rpy2=3.5.1=py310r41h3c8b411_1
  - scikit-learn=1.1.2=py310h3a564e9_0
  - scipy=1.9.1=py310h578b7cb_0
  - seaborn=0.12.0=hd8ed1ab_0
  - seaborn-base=0.12.0=pyhd8ed1ab_0
  - setuptools=65.4.1=pyhd8ed1ab_0
  - simplegeneric=0.8.1=py310haa95532_2
  - sip=6.6.2=py310h8a704f9_0
  - six=1.16.0=pyh6c4a22f_0
  - statsmodels=0.13.2=py310h2873277_0
  - tbb=2021.6.0=h91493d7_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.12=h8ffe710_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tornado=6.2=py310he2412df_0
  - tqdm=4.64.1=pyhd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022d=h191b570_0
  - tzlocal=2.1=py310haa95532_0
  - ucrt=10.0.20348.0=h57928b3_0
  - unicodedata2=14.0.0=py310he2412df_1
  - urllib3=1.26.11=pyhd8ed1ab_0
  - vc=14.2=hac3ee0b_8
  - vs2015_runtime=14.29.30139=h890b9b1_8
  - wheel=0.37.1=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=py310h5588dad_4
  - xorg-libxau=1.0.9=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.2.6=h8d14728_0
  - yacs=0.1.8=pyhd8ed1ab_0
  - yaml=0.2.5=h8ffe710_2
  - zlib=1.2.12=hcfcfb64_4
  - zstd=1.5.2=h7755175_4
