name: CytoCommunity
channels:
  - pyg
  - pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - bioconda
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - binutils_impl_linux-64=2.40=hf600244_0
  - blas=1.0=mkl
  - brotli=1.0.9=h166bdaf_8
  - brotli-bin=1.0.9=h166bdaf_8
  - bwidget=1.9.14=ha770c72_1
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.19.1=hd590300_0
  - ca-certificates=2023.5.7=hbcca054_0
  - cairo=1.16.0=ha61ee94_1014
  - certifi=2023.5.7=pyhd8ed1ab_0
  - charset-normalizer=3.1.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.0.7=py310hdf3cbec_0
  - cpuonly=2.0=0
  - curl=8.1.1=h409715c_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - expat=2.5.0=hcb278e6_1
  - ffmpeg=4.3=hf484d3e_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.39.4=py310h2372a71_0
  - freetype=2.12.1=hca18f0e_1
  - fribidi=1.0.10=h36c2ea0_0
  - gcc_impl_linux-64=12.2.0=hcc96c02_19
  - gettext=0.21.1=h27087fc_0
  - gfortran_impl_linux-64=12.2.0=h55be85b_19
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - graphite2=1.3.13=h58526e2_1001
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=12.2.0=hcc96c02_19
  - harfbuzz=6.0.0=h8e241bc_0
  - icu=70.1=h27087fc_0
  - idna=3.4=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - kernel-headers_linux-64=2.6.32=he073ed8_15
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py310hbf28c38_1
  - krb5=1.20.1=h81ceb04_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.0.9=h166bdaf_8
  - libbrotlidec=1.0.9=h166bdaf_8
  - libbrotlienc=1.0.9=h166bdaf_8
  - libcblas=3.9.0=12_linux64_mkl
  - libcurl=8.1.1=h409715c_0
  - libdeflate=1.17=h0b41bf4_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-devel_linux-64=12.2.0=h3b97bd3_19
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libglib=2.76.3=hebfc3b9_0
  - libgomp=12.2.0=h65d4601_19
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=12_linux64_mkl
  - libnghttp2=1.52.0=h61bc06f_0
  - libnsl=2.0.0=h7f98852_0
  - libpng=1.6.39=h753d276_0
  - libsanitizer=12.2.0=h46fd767_19
  - libsqlite=3.42.0=h2797004_0
  - libssh2=1.10.0=hf14f497_3
  - libstdcxx-devel_linux-64=12.2.0=h3b97bd3_19
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtiff=4.5.0=h6adf6a1_2
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.44.2=h166bdaf_0
  - libwebp-base=1.3.0=h0b41bf4_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.10.3=hca2bb57_4
  - libzlib=1.2.13=h166bdaf_4
  - make=4.3=hd18ef5c_1
  - markupsafe=2.1.2=py310h1fa729e_0
  - matplotlib-base=3.7.1=py310he60537e_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py310ha2c4b55_0
  - mkl_fft=1.3.1=py310h2b4bcf5_1
  - mkl_random=1.2.2=py310h00e6091_0
  - munkres=1.0.7=py_1
  - ncurses=6.3=h27087fc_1
  - nettle=3.6=he412f7d_0
  - numpy=1.24.3=py310hd5efca6_0
  - numpy-base=1.24.3=py310h8e6c178_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.1.0=hd590300_3
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=1.5.0=py310h769672d_0
  - pango=1.50.14=hd33c08f_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pcre2=10.40=hc3806b6_0
  - pillow=9.4.0=py310h023d228_1
  - pip=23.1.2=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - platformdirs=3.5.1=pyhd8ed1ab_0
  - pooch=1.7.0=pyha770c72_3
  - pthread-stubs=0.4=h36c2ea0_1001
  - pyg=2.1.0=py310_torch_1.11.0_cpu
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.6=ha86cf86_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=3_cp310
  - pytorch=1.11.0=py3.10_cpu_0
  - pytorch-cluster=1.6.0=py310_torch_1.11.0_cpu
  - pytorch-mutex=1.0=cpu
  - pytorch-scatter=2.0.9=py310_torch_1.11.0_cpu
  - pytorch-sparse=0.6.15=py310_torch_1.11.0_cpu
  - pytz=2023.3=pyhd8ed1ab_0
  - r=4.2=r42hd8ed1ab_1006
  - r-base=4.2.3=ha7d60f8_0
  - r-boot=1.3_28.1=r42hc72bb7e_0
  - r-class=7.3_22=r42h57805ef_0
  - r-cluster=2.1.4=r42h8da6f51_0
  - r-codetools=0.2_19=r42hc72bb7e_0
  - r-foreign=0.8_84=r42h133d619_0
  - r-kernsmooth=2.23_21=r42h13b3f57_0
  - r-lattice=0.21_8=r42h133d619_0
  - r-mass=7.3_60=r42h57805ef_0
  - r-matrix=1.5_4.1=r42h316c678_0
  - r-mgcv=1.8_42=r42he1ae0d6_0
  - r-nlme=3.1_162=r42hac0b197_0
  - r-nnet=7.3_19=r42h57805ef_0
  - r-recommended=4.2=r42hd8ed1ab_1005
  - r-rpart=4.1.19=r42h06615bd_0
  - r-spatial=7.3_16=r42h133d619_0
  - r-survival=3.5_5=r42h133d619_0
  - readline=8.2=h8228510_1
  - requests=2.31.0=pyhd8ed1ab_0
  - scikit-learn=1.2.2=py310h41b6a48_1
  - scipy=1.10.1=py310hd5efca6_0
  - seaborn=0.12.0=hd8ed1ab_0
  - seaborn-base=0.12.0=pyhd8ed1ab_0
  - sed=4.8=he412f7d_0
  - setuptools=67.7.2=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - statsmodels=0.14.0=py310h278f3c1_1
  - sysroot_linux-64=2.12=he073ed8_15
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.12=h27826a3_0
  - tktable=2.10=hb7b940f_3
  - torchaudio=0.11.0=py310_cpu
  - torchvision=0.12.0=py310_cpu
  - tqdm=4.65.0=pyhd8ed1ab_1
  - typing-extensions=4.6.0=hd8ed1ab_0
  - typing_extensions=4.6.0=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - unicodedata2=15.0.0=py310h5764c6d_0
  - urllib3=2.0.2=pyhd8ed1ab_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxt=1.2.1=h7f98852_2
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=h3eb15da_6
prefix: /home/dell/anaconda3/envs/CytoCommunity
